name:  bootfi_flutter_template
description: This is a template for all of our projects in Bootfi.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter
 # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

 # Packages that we use almost all our projects
  flutter_launcher_icons: # Change app icon
  sentry_flutter: # Add sentry error tracking
  cached_network_image: # Cached network image package
  shared_preferences: #For local caching


dev_dependencies:
  flutter_test:
    sdk: flutter
# Packages that we use almost all our projects
flutter_icons:
  image_path_android: "assets/images/android_app_icon.png"
  image_path_ios: "assets/images/ios_app_icon.png"
  android: true
  ios: true
  remove_alpha_ios: true

  build_runner:  # generate dart files
  freezed:
  freezed_annotation:
  json_serializable:
  change_app_package_name:
  rename:

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices.
  flutter_lints: ^2.0.0


# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/


  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section.
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

